# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MEDical Image Computing Lab (MEDIC)
email: rdamseh@uaeu.ac.ae
description: >-
  AI and Machine Learning for Medical Image Computing and Automated Dignostics at
  United Arab Emirates University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://damseh.github.io" # the base hostname & protocol for your site

# Author settings
author:
  name: Dr. Rafat Damseh
  bio: >-
    Assistant Professor in Computer Science and Software Engineering at UAE University.
  avatar: /assets/images/profile.jpg
  email: rdamseh@uaeu.ac.ae

# Lab information
lab:
  name: Medical Image Computing Lab
  head: Dr. Rafat Damseh
  university: United Arab Emirates University
  department: Computer Science and Software Engineering
  address: Room 3070, P.O. Box 15551, Al Ain, UAE

# Social links
github_username: Damseh
google_scholar_id: vmQUi8AAAAAJ&hl=en&oi=ao
twitter_username: # Add if you have one

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

